-- Migration number: 0001 	 init
-- Scores: one row per finished run. `id` is generated by the game client so a
-- later name change can update the same run instead of duplicating it.
CREATE TABLE IF NOT EXISTS scores (
  id TEXT PRIMARY KEY,
  game TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT 'PILOT',
  score INTEGER NOT NULL,
  wave INTEGER NOT NULL DEFAULT 0,
  difficulty TEXT NOT NULL DEFAULT 'veteran',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_scores_game_score ON scores (game, score DESC);
CREATE INDEX IF NOT EXISTS idx_scores_game_created ON scores (game, created_at);

-- Newsletter signups from the landing page.
CREATE TABLE IF NOT EXISTS signups (
  email TEXT PRIMARY KEY,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
